version: '3'

services:
  db:
    container_name: container-db
    image: mysql:latest
    ports:
      - 13306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=ezops
      - MYSQL_DATABASE=ezops
      - MYSQL_PASSWORD=ezopsezops

  server:
    container_name: container-server
    image: image-server
    build:
        context: ./server
        dockerfile: ser.Dockerfile
    depends_on:
      - db
    ports:
      - '8080:8080'
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=ezops
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=ezopsezops
      - DATABASE_PORT=3306

  client:
    container_name: container-client
    build:
      context: ./client
      dockerfile: cli.Dockerfile
    image: image-client
    volumes:
      - ./client:/usr/src/app
    ports:
      - '3000:3000'
    command: npm start
