version: '3'

services: 
  db:
    container_name: docker_mysql
    image: mysql:latest
    ports:
      - 3306:3306 
    environment:
      - MYSQL_ROOT_PASSWORD=ezops
      - MYSQL_DATABASE=ezops
      - MYSQL_PASSWORD=ezopsezops
  spring_backend:
    container_name: gradle-springboot-docker
    image: spring_image
    build:
        context: ./
        dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=docker_mysql
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=ezopsezops
      - DATABASE_NAME=ezops  
      - DATABASE_PORT=3306
