package com.example.dbchartgenerator;

import org.springframework.web.bind.annotation.RestController;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.example.dbchartgenerator.Model.Data;


/*
@RestController
public class HelloController {

    @Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	  private DataRepo dataRepository;

    @RequestMapping("/")
    public String index() {

      Data n = new Data();

      // Parse columns
      n.setId(1);
  		n.setName("DAEUN");
  		n.setEmail("daeunn@gmail.com");
  		dataRepository.save(n);

      return "Greetings from Spring Boot!";
    }

}
*/
